failurePolicy: "Fail"
onlyMarkedNamespaces: # Only namespaces with itsfriday/webhookenabled label set to validate would be checked
  enabled: false
  mode: "validate" # validate or ignore
                   # if validate - only namespaces with itsfriday/webhookenabled=validate would be checked
                   # if ingnore - only namespaces with itsfriday/webhookenabled=ignore would be ignored
replicasCount: 2
images:
  itsfriday: razikus/its-friday-k8s-admission-controller:rust1.0.0
service:
  port: 443
envs:
  MY_FRIDAY: "4"
