apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "itsfriday.name" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
