apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: "{{$.Release.Namespace}}"
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/name: {{ include "itsfriday.name" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}